### ISSUE TITLE
Clean up camera blob mess

### ISSUE THREAD

**Issue by minz1** [Galaxy-MSM8953/android_device_samsung_msm8953-common#1]
Some of the camera blobs can be commonized, some not so much. We need to clean it up and figure out what can and can't be commonized

**Comment by aapav01** [comment]
Actually, DRM files are messing with the Camera blobs on my device.. I need to work on the complete blobs list.. once my all falt error are fixed i feel my camera would work

**Comment by aapav01** [comment]
fixed
